### ISSUE TITLE
Make sure failure in each order does not affect the rest of the order book.

### ISSUE THREAD

**Issue by Zergity** [nextyio/nytex#14]
Overflow or any exception in matching/comparing order will make that particular order skipped. Do not break the contract call for 1 bad order.

**Comment by bestboyvn87** [comment]
suggest : all inputs must be less than 2 ** 128. (about 10 **  34) This should solve all problems with overflows.
Proofs:
Total supply of NTY is about 10 ** 30 wei << 10 ** 34 (enough safe in all cases).
NUSD supply of the wall is about 10 ** 31 wei (decimal = 18) (enough safe for long term).
