### ISSUE TITLE
Create orderToFill to calculate how much tokens has to be filled

### ISSUE THREAD

**Issue by Zergity** [nextyio/nytex#9]
Calculate a single order to fill as much as a given StableToken Amount.

* orderToFill(BuyType, 123) returns an SellType order to fill enough buying orders to burn as much as 123 StableToken.
* orderToFill(SellType, 456) returns an BuyType order to fill enough selling orders to create as much as 456 StableToken.

The returned sell order must be filled completedly, with nothing remain after.

**Comment by bestboyvn87** [comment]
solved.
